name: Setup & Run Playwright Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Needed to push to gh-pages
  pages: write     # Needed for GitHub Pages deployment
  id-token: write  # Needed for GitHub Pages deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout main branch
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Set up Python 3.13
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # ✅ Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # ✅ Install only required Playwright browsers
      - name: Install Playwright browsers
        run: python -m playwright install chromium webkit firefox 

      # ✅ Run Playwright tests in headless mode and save Allure results
      - name: Run Playwright Tests
        run: pytest --alluredir=allure-results --browser chromium -v -s
        continue-on-error: true

      # ✅ Retrieve Allure report history (from gh-pages)
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # ✅ Generate Allure Report
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      # ✅ Deploy Allure Report to GitHub Pages
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history